import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#301216',
        'surface-tint': '#34e507',
        'inverse-surface': '#e2e2e2',
        'secondary': '#ffb86b',
        'surface-container-high': '#282a2b',
        'surface': '#121414',
        'on-primary-fixed-variant': '#0c5300',
        'on-surface-variant': '#bbccb0',
        'tertiary': '#ffefef',
        'on-secondary-fixed-variant': '#683d00',
        'bg-surface': '#15181E',
        'secondary-fixed': '#ffdcbc',
        'background': '#121414',
        'surface-container': '#1e2020',
        'inverse-on-surface': '#2f3131',
        'on-secondary-fixed': '#2c1700',
        'on-surface': '#e2e2e2',
        'tertiary-container': '#ffc9cd',
        'outline-variant': '#3c4b36',
        'secondary-container': '#ed9000',
        'on-primary-container': '#136c00',
        'inverse-primary': '#136e00',
        'on-primary': '#063900',
        'on-secondary-container': '#583300',
        'on-tertiary': '#48272a',
        'surface-dim': '#121414',
        'border-subtle': '#30363D',
        'surface-container-highest': '#333535',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#34e507',
        'on-tertiary-container': '#7b5256',
        'text-muted': '#B8B8B8',
        'on-tertiary-fixed-variant': '#623c40',
        'surface-container-low': '#1a1c1c',
        'error': '#ffb4ab',
        'surface-container-lowest': '#0c0f0f',
        'primary-container': '#4af626',
        'error-container': '#93000a',
        'bg-main': '#0B0C0F',
        'on-secondary': '#492900',
        'primary-fixed': '#79ff59',
        'surface-variant': '#333535',
        'tertiary-fixed-dim': '#eeb9bd',
        'primary': '#d4ffc1',
        'tertiary-fixed': '#ffdadc',
        'surface-bright': '#38393a',
        'on-error': '#690005',
        'on-primary-fixed': '#022100',
        'on-background': '#e2e2e2',
        'outline': '#86957d',
        'secondary-fixed-dim': '#ffb86b',
        'glow-green': 'rgba(74, 246, 38, 0.25)',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'gutter': '24px',
        'container-padding': '16px',
        'max-width': '1200px',
        'section-gap': '120px',
        'section-gap-mobile': '64px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['IBM Plex Mono', 'monospace'],
        'display-lg-mobile': ['IBM Plex Mono', 'monospace'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['IBM Plex Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'code-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};

export default config;
